### ISSUE TITLE
Not query multiple disputes from each node

### ISSUE THREAD

**Issue by abramsymons** [zellular-xyz/zsequencer#10]
Currently, we are querying each node multiple times to dispute confirmation if we have censored txs from various apps or have other issues like detecting the sequencer to be offline. 

https://github.com/zellular-xyz/zsequencer/blob/0bb292ad4a2e661d0e0c9d149ea58c4ce9f513ff/node/tasks.py#L223-L248

All censored txs can be gathered before looping over nodes to gather dispute confirmations from them and send all missed txs from different apps together. Getting dispute confirmation when the sequencer is down can also be done in the same request.

**Comment by mchitgarha78** [comment]
Fixed in the commit above.
