### ISSUE TITLE
Send dispute requests in parallel

### ISSUE THREAD

**Issue by abramsymons** [zellular-xyz/zsequencer#9]
The current implementation is sending dispute requests synchronously: 

https://github.com/zellular-xyz/zsequencer/blob/66a1fd00946cdf5fa9fe0299ed6e5643010bcc6b/node/tasks.py#L217

It should be updated to query disputes in parallel.

**Comment by mchitgarha78** [comment]
Created branch [issue-123-brief-description](https://github.com/zellular-xyz/zsequencer/tree/issue-9-send-parallel-dispute-requests) to address this issue.

**Comment by mchitgarha78** [comment]
Fixed in the commit above.
